=== KIT-IAI/GMLToolbox-src/AppConfig/XSD/Nutzungsprofile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
 <xs:element name="Nutzungsprofile">
  <xs:complexType>
   <xs:sequence minOccurs="0" maxOccurs="unbounded">
    <xs:choice>
    <xs:element ref="Nutzungsprofil"/>
     <xs:element ref="NutzungsprofilKomplex"/>
    <xs:element name="NutzungsprofilGruppe" type="NutzungsprofilGruppeType"/>
    </xs:choice>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
 
 <xs:complexType name="NutzungsprofilGruppeType">
  <xs:sequence>
   <xs:element name="heizung" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="heizungBetrieb" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="kuehlung" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="kuehlungBetrieb" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="lueftung" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="beleuchtung" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="personen" type="NutzungsprofilGruppeMemberType"/>
   <xs:element name="geraete" type="NutzungsprofilGruppeMemberType"/>   
  </xs:sequence>
  <xs:attribute name="name" type="xs:string"/>
 </xs:complexType>
 
 <xs:complexType name="NutzungsprofilGruppeMemberType" mixed="false">  
  <xs:attribute name="ref" type="xs:IDREF"/>
 </xs:complexType>
 
 <xs:element name="Nutzungsprofil" type="NutzungsprofilType"/>
 
 <xs:complexType name="NutzungsprofilType">
  <xs:sequence>
   <xs:element name="name" type="xs:ID"/>
   <xs:element name="description" type="xs:string" minOccurs="0"/>   
   <xs:element name="aktiv" type="xs:boolean" minOccurs="0" default="true"/>
   <xs:element name="periode" minOccurs="1" maxOccurs="unbounded">
    <xs:complexType>
     <xs:sequence>
      <xs:element name="zeitreihe" type="DailyTimeSeriesType" minOccurs="0" maxOccurs="unbounded"/>
     </xs:sequence>
     <xs:attribute name="startDay" type="xs:int" use="required"/>
     <xs:attribute name="startMonth" type="xs:int" use="required"/>
     <xs:attribute name="endDay" type="xs:int" use="required"/>
     <xs:attribute name="endMonth" type="xs:int" use="required"/>
    </xs:complexType>
   </xs:element>  
  </xs:sequence>
 </xs:complexType>
 
 <xs:element name="NutzungsprofilKomplex" type="NutzungsprofilKomplexType"/>
 
 <xs:complexType name="NutzungsprofilKomplexType">
  <xs:sequence>
  <xs:element name="name" type="xs:ID"/>
  <xs:element name="description" type="xs:string" minOccurs="0"/>   
  <xs:element name="aktiv" type="xs:boolean" minOccurs="0" default="true"/>
   <xs:element name="period" type="NutzungsprofilKomplexMemberType" minOccurs="1" maxOccurs="unbounded"/>   
  </xs:sequence>  
 </xs:complexType>
 
 <xs:complexType name="NutzungsprofilKomplexMemberType">
  <xs:attribute name="anteil" type="xs:decimal" use="required"/>
  <xs:attribute name="profil" type="xs:IDREF"/>
 </xs:complexType>
 
 <xs:element name="NutzungsprofilBetrieb" type="NutzungsprofilBetriebType" substitutionGroup="Nutzungsprofil"/>
 <xs:complexType name="NutzungsprofilBetriebType">
  <xs:complexContent >
   <xs:extension base="NutzungsprofilType">
    <xs:sequence>
     <xs:element name="system" type="SystemType"/>
    </xs:sequence>    
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
  
 <xs:element name="NutzungsprofilHeizung" type="NutzungsprofilHeizungType" substitutionGroup="Nutzungsprofil"/>
 <xs:complexType name="NutzungsprofilHeizungType">
  <xs:complexContent >
   <xs:extension base="NutzungsprofilType">
    
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 
 <xs:element name="NutzungsprofilKuehlung" type="NutzungsprofilKuehlungType" substitutionGroup="Nutzungsprofil"/>
 
 <xs:complexType name="NutzungsprofilKuehlungType">
  <xs:complexContent >
   <xs:extension base="NutzungsprofilType">    
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 
 <xs:element name="NutzungsprofilLueftung" type="NutzungsprofilLueftungType" substitutionGroup="Nutzungsprofil"/>
 
 <xs:complexType name="NutzungsprofilLueftungType">
  <xs:complexContent >
   <xs:extension base="NutzungsprofilType">    
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 
 <xs:element name="NutzungsprofilBeleuchtung" type="NutzungsprofilBeleuchtungType" substitutionGroup="Nutzungsprofil"/>
 
 <xs:complexType name="NutzungsprofilBeleuchtungType">
  <xs:complexContent >
   <xs:extension base="NutzungsprofilType">
    <xs:sequence>
     <xs:element name="automatisch" type="xs:boolean" minOccurs="0" default="false"/>
     <xs:element name="konvektAnteil" type="xs:double" minOccurs="0" default="50"/>    
     <xs:element name="maxHelligkeit" type="xs:double" minOccurs="0" default="0"/>
     <xs:element name="effizienz" type="xs:double" minOccurs="0" default="50"/>      
     <xs:element name="maxWaermeleistung" type="xs:double" minOccurs="0" default="0"/>                     
    </xs:sequence>    
   </xs:extension>
  </xs:complexContent>
 </xs:complexType> 
 
 <xs:element name="NutzungsprofilPersonen" type="NutzungsprofilPersonenType" substitutionGroup="Nutzungsprofil"/>
 
 <xs:complexType name="NutzungsprofilPersonenType">
  <xs:complexContent>
   <xs:extension base="NutzungsprofilType">
    <xs:sequence>
     <xs:element name="waermeleistungPerson" type="xs:double"/>
     <xs:element name="konvektAnteil" type="xs:double" minOccurs="0" default="50"/>   
     <xs:element name="flaecheProPerson" type="xs:double" minOccurs="0" default="0"/>
     <xs:element name="maxAnzahlPersonen" type="xs:double" minOccurs="0" default="0"/>     
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
 
 <xs:element name="NutzungsprofilGeraete" type="NutzungsprofilGereateType" substitutionGroup="Nutzungsprofil"/>
 
 <xs:complexType name="NutzungsprofilGereateType">
  <xs:complexContent>
   <xs:extension base="NutzungsprofilType">
    <xs:sequence>    
     <xs:element name="konvektAnteil" type="xs:double" minOccurs="0" default="50"/>   
     <xs:element name="maxWaermeleistung" type="xs:double"/>         
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType> 
 
 <xs:simpleType name="SystemType">
  <xs:restriction base="xs:string">
   <xs:enumeration value="heating"/>
   <xs:enumeration value="cooling"/>
   <xs:enumeration value="ventilation"/>
  </xs:restriction>
 </xs:simpleType>  

 
 <xs:complexType name="DailyTimeSeriesType">
  <xs:sequence>
   <xs:element name="day" type="DayType"/>
   <xs:element name="uom" type="xs:string"/>
   <xs:element name="values" type="ValuesType"/>
  </xs:sequence>
  <xs:attribute name="minValue" type="xs:double" use="required"/>
  <xs:attribute name="maxValue" type="xs:double" use="required"/>
  <xs:attribute name="defaultValue" type="xs:double" use="required"/>
 </xs:complexType>
 
 <xs:simpleType name="DayType">
  <xs:restriction base="xs:string">
   <xs:enumeration value="monday"/>
   <xs:enumeration value="tuesday"/>
   <xs:enumeration value="wednesday"/>
   <xs:enumeration value="thursday"/>
   <xs:enumeration value="friday"/>
   <xs:enumeration value="saturday"/>
   <xs:enumeration value="sunday"/>
   <xs:enumeration value="designDay"/>
   <xs:enumeration value="weekDay"/>
   <xs:enumeration value="weekEnd"/>
   <xs:enumeration value="typicalDay"/>
  </xs:restriction>
 </xs:simpleType>
 
 
 <xs:simpleType name="ValuesType">
  <xs:restriction>
   <xs:simpleType>
    <xs:list itemType="xs:double"/>
   </xs:simpleType>
   <xs:minLength value="24"/>
   <xs:maxLength value="24"/>
  </xs:restriction>
 
 </xs:simpleType>
</xs:schema>

=== KIT-IAI/GMLToolbox-src/AppConfig/NutzungsprofilListe.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!--Erzeugt mit KIT (www.kit.edu) GML-Toolbox, Erstellungsdatum: 02/01/19-->
<Nutzungsprofile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/Nutzungsprofile.xsd">
 

<!--====================================================================================================-->
<!--                ASHRAE Profile                                                                      -->
<!--====================================================================================================--> 
 <NutzungsprofilGeraete>
    <name>ASHRAE-140-600-Geraete</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
     <day>typicalDay</day>
     <uom>scale</uom>
     <values>1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.</values>
    </zeitreihe>
   </periode>    
    <konvektAnteil>40</konvektAnteil>
    <maxWaermeleistung>4.166667</maxWaermeleistung>
  </NutzungsprofilGeraete>
 
  <NutzungsprofilHeizung>
    <name>ASHRAE-140-600-Heizung</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="5" maxValue="25" defaultValue="20">
     <day>typicalDay</day>
     <uom>C</uom>
     <values>20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20.</values>
    </zeitreihe>
  </periode>    
  </NutzungsprofilHeizung>
 
  <NutzungsprofilLueftung>
    <name>ASHRAE-140-600-Lueftung</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="15" defaultValue="0.5">
      <day>typicalDay</day>
      <uom>1/h</uom>
      <values>0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5</values>
    </zeitreihe>
   </periode>
  </NutzungsprofilLueftung>
 
  <NutzungsprofilKuehlung>
    <name>ASHRAE-140-600-Kuehlung</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="5" maxValue="35" defaultValue="27">
      <day>typicalDay</day>
      <uom>C</uom>
      <values>27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27. 27.</values>
    </zeitreihe>
   </periode>
  </NutzungsprofilKuehlung>
 
 <NutzungsprofilBeleuchtung>
  <name>KeineBeleuchtung</name>
  <aktiv>false</aktiv>
  <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
   <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
    <day>typicalDay</day>
    <uom>scale</uom>
    <values>0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</values>
   </zeitreihe>
  </periode>
  <automatisch>false</automatisch>
  <konvektAnteil>50</konvektAnteil>
  <maxHelligkeit>200</maxHelligkeit>
  <effizienz>50</effizienz>
  <maxWaermeleistung>4</maxWaermeleistung>
 </NutzungsprofilBeleuchtung>
 
 <NutzungsprofilPersonen>
  <name>KeinePersonen</name>
  <aktiv>false</aktiv>
  <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
   <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
    <day>typicalDay</day>
    <uom>scale</uom>
    <values>0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</values>
   </zeitreihe>
  </periode>
  <waermeleistungPerson>0</waermeleistungPerson>
  <konvektAnteil>50</konvektAnteil>
  <flaecheProPerson>INF</flaecheProPerson>
 </NutzungsprofilPersonen>
 
 <NutzungsprofilBetrieb>
  <name>On-7h-18h</name>
  <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
   <zeitreihe minValue="0" maxValue="1" defaultValue="0">
    <day>typicalDay</day>
    <uom>-</uom>
    <values>0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0</values>
   </zeitreihe>
  </periode>
  <system>cooling</system>
 </NutzungsprofilBetrieb>
 
 <NutzungsprofilLueftung>
  <name>ASHRAE-140-650-Lueftung</name>
  <aktiv>true</aktiv>
  <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
   <zeitreihe minValue="0" maxValue="15" defaultValue="0.5">
    <day>typicalDay</day>
    <uom>1/h</uom>
    <values>13.142 13.142 13.142 13.142 13.142 13.142 13.142 0 0 0 0 0 0 0 0 0 0 0 13.142 13.142 13.142 13.142 13.142 13.142</values>
   </zeitreihe>
  </periode>
 </NutzungsprofilLueftung>
 
 <!--====================================================================================================-->
 <!--                Profile Bau 445                                                                     -->
 <!--====================================================================================================--> 
  <NutzungsprofilBeleuchtung>
    <name>Bau-445-Beleuchtung</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekDay</day>
      <uom>scale</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.</values>
    </zeitreihe>
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekEnd</day>
      <uom>scale</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</values>
    </zeitreihe>
   </periode>
    <automatisch>false</automatisch>
    <konvektAnteil>50</konvektAnteil>
    <maxHelligkeit>200</maxHelligkeit>
    <effizienz>50</effizienz>
    <maxWaermeleistung>4</maxWaermeleistung>
  </NutzungsprofilBeleuchtung>
 
  <NutzungsprofilGeraete>
    <name>Bau-445-Geräte</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekDay</day>
      <uom>scale</uom>
      <values>0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.4 0.8 0.8 0.4 0.2 0.4 0.8 0.8 0.2 0.1 0.1 0.1 0.1 0.1 0.1 0.1</values>
    </zeitreihe>
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekEnd</day>
      <uom>scale</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</values>
    </zeitreihe>
   </periode>
    <konvektAnteil>50</konvektAnteil>
    <maxWaermeleistung>5</maxWaermeleistung>
  </NutzungsprofilGeraete>
 
  <NutzungsprofilHeizung>
    <name>Bau-445-Heizung</name>
    <description>Konstante Tageswerte ohne Nachtabsenkung</description>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="17" maxValue="23" defaultValue="21">
      <day>weekDay</day>
      <uom>C</uom>
      <values>21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21.</values>
    </zeitreihe>
    <zeitreihe minValue="17" maxValue="22" defaultValue="18">
      <day>weekEnd</day>
      <uom>C</uom>
      <values>21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21. 21.</values>
    </zeitreihe>
   </periode>
  </NutzungsprofilHeizung>
 
  <NutzungsprofilKuehlung>
    <name>Bau-445-Kuehlung</name>
    <description>Keine Kühlung</description>
    <aktiv>false</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="15" maxValue="30" defaultValue="25">
      <day>typicalDay</day>
      <uom>C</uom>
      <values>25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25. 25.</values>
    </zeitreihe>
   </periode>
  </NutzungsprofilKuehlung>
 
  <NutzungsprofilLueftung>
    <name>Bau-445-Lüftung</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="2" defaultValue="0.5">
      <day>weekDay</day>
      <uom>1/h</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 1.2 0. 0.</values>
    </zeitreihe>
    <zeitreihe minValue="0" maxValue="2" defaultValue="0.5">
      <day>weekEnd</day>
      <uom>1/h</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</values>
    </zeitreihe>
   </periode>
  </NutzungsprofilLueftung>
 
  <NutzungsprofilPersonen>
    <name>Bau-445-Personen</name>
    <description>Maximale Anwesenheit zwischen 8h und 18h</description>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekDay</day>
      <uom>scale</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 0.2 0.4 0.6 0.8 0.8 0.4 0.6 0.8 0.8 0.4 0.2 0. 0. 0. 0. 0. 0.</values>
    </zeitreihe>
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekEnd</day>
      <uom>scale</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.</values>
    </zeitreihe>
   </periode>
    <waermeleistungPerson>82</waermeleistungPerson>
    <konvektAnteil>50</konvektAnteil>
    <flaecheProPerson>32.851189091868</flaecheProPerson>   
  </NutzungsprofilPersonen>
 
 <!--====================================================================================================-->
 <!--                Profile DIN 18500-10 Gruppenbüro                                                    -->
 <!--====================================================================================================--> 
  <NutzungsprofilBeleuchtung>
    <name>DIN_18599_10_GruppenbüroBeleuchtung</name>
    <aktiv>true</aktiv>
   <periode startDay="1" startMonth="1" endDay="31" endMonth="12">
    <zeitreihe minValue="0" maxValue="1" defaultValue="0.5">
      <day>weekDay</day>
      <uom>scale</uom>
      <values>0. 0. 0. 0. 0. 0. 0. 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0. 0. 0. 0. 0. 0.</values>
