=== KIT-IAI/GMLToolbox-src/AppConfig/XSD/SvgParameter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by Dr. Joachim Benner (Institut fÃ¼r Angewandte Informatik Forschungszentrum Karlsruhe) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="SvgVisualisierung">
		<xs:annotation>
			<xs:documentation>Parameter Gml-Visualisierung mit SVG</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="GmlKlassenVisual" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Style" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Symbol" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Marker" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Pattern" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Hatching" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Enumeration" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="FlaechenDarstellung" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="LinienDarstellung" minOccurs="0" maxOccurs="1"/>
			</xs:choice>
			<xs:attribute name="gmlType" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="XPLANGML_2_0"/>
						<xs:enumeration value="XPLANGML_3_0"/>
						<xs:enumeration value="XPLANGML_4_0"/>
						<xs:enumeration value="XPLANGML_4_1"/>
					 <xs:enumeration value="XPLANGML_5_0"/>
					 <xs:enumeration value="XPLANGML_5_1"/>
					 <xs:enumeration value="XPLANGML_5_2"/>
						<xs:enumeration value="INSPIRE_LU_EXISTING"/>
						<xs:enumeration value="INSPIRE_LU_PLANNED"/>
						<xs:enumeration value="NAS_5_1"/>
						<xs:enumeration value="NAS_5_1_1"/>
						<xs:enumeration value="NAS_6_0"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="datum" type="xs:date" use="optional"/>
			<xs:attribute name="Masstab" type="xs:string" use="optional"/>
			<xs:attribute name="breiteUeberschrift" type="xs:int" use="optional"/>
			<xs:attribute name="hoeheUeberschrift" type="xs:int" use="optional"/>
			<xs:attribute name="gmlVersion" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="GmlKlassenVisual">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Darstellung" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="gmlKlassenName" type="xs:string" use="required"/>
			<xs:attribute name="priorityFlaechendarstellung" type="xs:int" use="optional"/>
			<xs:attribute name="priorityLiniendarstellung" type="xs:int" use="optional"/>
			<xs:attribute name="priorityPunktdarstellung" type="xs:int" use="optional"/>
			<xs:attribute name="selectAttribut1" type="xs:string" use="optional"/>
			<xs:attribute name="selectAttribut2" type="xs:string" use="optional"/>
			<xs:attribute name="selectAttribut3" type="xs:string" use="optional"/>
			<xs:attribute name="defaultSymbol" type="xs:IDREF" use="optional"/>
			<xs:attribute name="defaultSymbolSize" type="xs:float" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Darstellung" type="DarstellungType" abstract="true"/>
	<xs:complexType name="DarstellungType">
		<xs:sequence>
			<xs:element name="SelectAttributWert1" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SelectAttributWert2" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="SelectAttributWert3" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="default" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
		<xs:attribute name="priority" type="xs:int" use="optional"/>
	</xs:complexType>
	<xs:element name="FlaechenDarstellung" substitutionGroup="Darstellung">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="DarstellungType">
					<xs:sequence>
						<xs:element ref="FlaechenParams" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="LineTextParams" minOccurs="0"/>
						<xs:element ref="LineSymbolParams" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="deckend" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="LinienDarstellung" substitutionGroup="Darstellung">
		<xs:complexType>
			
			<xs:complexContent>
				<xs:extension base="DarstellungType">
					<xs:sequence>
						<xs:element ref="LinienParams" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="LineTextParams" minOccurs="0"/>
						<xs:element ref="LineSymbolParams" minOccurs="0"/>
					</xs:sequence>
					<xs:attribute name="startMarker" use="optional" type="xs:IDREF"/>		
					<xs:attribute name="endMarker" use="optional" type="xs:IDREF"/>	
				</xs:extension>
			</xs:complexContent>
					
		</xs:complexType>
		
	</xs:element>
	<xs:element name="PunktDarstellung" substitutionGroup="Darstellung">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="DarstellungType">
					<xs:attribute name="attributA" type="xs:string" use="optional"/>
					<xs:attribute name="attributB" type="xs:string" use="optional"/>
					<xs:attribute name="textStyle" type="xs:IDREF" use="optional"/>
					<xs:attribute name="textOffsetX" type="xs:double" use="optional"/>
					<xs:attribute name="textOffsetY" type="xs:double" use="optional"/>
					<xs:attribute name="symbol" type="xs:string" use="optional"/>
					<xs:attribute name="symbolSize" type="xs:double" use="optional"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:annotation>
		<xs:documentation>-----------  Farbe------------------------------------------</xs:documentation>
	</xs:annotation>
	<xs:complexType name="ColorType">
		<xs:attribute name="r" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="g" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="b" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:int">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="255"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="None"/>
	<xs:element name="ColorName">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="aqua"/>
				<xs:enumeration value="black"/>
				<xs:enumeration value="blue"/>
				<xs:enumeration value="fuchsia"/>
				<xs:enumeration value="gray"/>
				<xs:enumeration value="green"/>
				<xs:enumeration value="lime"/>
				<xs:enumeration value="maroon"/>
				<xs:enumeration value="navy"/>
				<xs:enumeration value="olive"/>
				<xs:enumeration value="purple"/>
				<xs:enumeration value="red"/>
				<xs:enumeration value="silver"/>
				<xs:enumeration value="teal"/>
				<xs:enumeration value="white"/>
				<xs:enumeration value="yellow"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Color">
		<xs:complexType mixed="0">
			<xs:complexContent mixed="0">
				<xs:extension base="ColorType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="FillColor">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="None"/>
				<xs:element ref="ColorName"/>
				<xs:element ref="Color"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="StrokeColor">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="None"/>
				<xs:element ref="ColorName"/>
				<xs:element ref="Color"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:annotation>
		<xs:documentation>---------- Symbole</xs:documentation>
	</xs:annotation>
	<xs:element name="Symbol">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="Path"/>
				<xs:element ref="Circle"/>
				<xs:element ref="Rect"/>
				<xs:element ref="Text"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:ID" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Style">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FillColor"/>
				<xs:element ref="StrokeColor"/>
				<xs:element name="Fill-opacity" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:float">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Stroke-width" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:float">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Stroke-linecap" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="butt"/>
							<xs:enumeration value="round"/>
							<xs:enumeration value="square"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Stroke-dasharray" type="xs:float" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Stroke-dashoffset" type="xs:int" minOccurs="0"/>
				<xs:element name="Font-size" type="xs:float" minOccurs="0"/>
				<xs:element name="Font-weight" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="bold"/>
							<xs:enumeration value="lighter"/>
							<xs:enumeration value="normal"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Font-family" type="xs:string" minOccurs="0"/>
				<xs:element name="Kerning" type="xs:float" minOccurs="0"/>
				<xs:element name="Baseline-shift" type="xs:float" minOccurs="0"/>
				<xs:element name="Baseline-shift-uom" type="xs:string" minOccurs="0"/>
				<xs:element name="Text-anchor"  minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="start"/>
							<xs:enumeration value="middle"/>
							<xs:enumeration value="end"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="styleName" type="xs:ID" use="required"/>
			<xs:attribute use="optional" type="xs:boolean" name="scalable">
				
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Path">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FillColor" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="StrokeColor" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Stroke-width" type="xs:float" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Stroke-dasharray" type="xs:float" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:IDREF" use="optional"/>
			<xs:attribute name="path" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Circle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FillColor" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="StrokeColor" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Stroke-width" type="xs:float" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Stroke-dasharray" type="xs:float" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:IDREF" use="optional"/>
			<xs:attribute name="cx" type="xs:float" use="required"/>
			<xs:attribute name="cy" type="xs:float" use="required"/>
			<xs:attribute name="r" type="xs:float" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Rect">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FillColor" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="StrokeColor" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Stroke-width" type="xs:float" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Stroke-dasharray" type="xs:float" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="class" type="xs:IDREF" use="optional"/>
			<xs:attribute name="x" type="xs:float" use="optional" default="0.0"/>
			<xs:attribute name="y" type="xs:float" use="optional" default="0.0"/>
			<xs:attribute name="width" type="xs:float" use="required"/>
			<xs:attribute name="height" type="xs:float" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Text">
		<xs:complexType>
			<xs:attribute name="class" type="xs:string" use="required"/>
			<xs:attribute name="size" type="xs:float" use="required"/>
			<xs:attribute name="x" type="xs:float" use="required"/>
			<xs:attribute name="y" type="xs:float" use="required"/>
			<xs:attribute name="text" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Pattern">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="Path"/>
				<xs:element ref="Circle"/>
				<xs:element ref="Rect"/>
				<xs:element ref="Text"/>
			</xs:choice>
			<xs:attribute name="name" type="xs:ID" use="required"/>
			<xs:attribute name="x" type="xs:float" use="required"/>
			<xs:attribute name="y" type="xs:float" use="required"/>
			<xs:attribute name="width" type="xs:float" use="required"/>
			<xs:attribute name="height" type="xs:float" use="required"/>
			<xs:attribute name="angle" type="xs:float" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Hatching">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="stroke-width" type="xs:float"/>
				<xs:element name="line-dist" type="xs:float"/>
				<xs:element ref="StrokeColor"/>
				<xs:element ref="FillColor"/>
				<xs:element name="HatchingType">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="horizontal"/>
							<xs:enumeration value="vertical"/>
							<xs:enumeration value="chequered"/>
							<xs:enumeration value="lowerLeftToUpperRight"/>
							<xs:enumeration value="upperLeftToLowerRight"/>
							<xs:enumeration value="crossed"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:ID" use="required"/>	
		</xs:complexType>
	</xs:element>
	<xs:element name="FlaechenParams">
		<xs:complexType>
			<xs:attribute name="class" type="xs:IDREF" use="optional"/>
			<xs:attribute name="clip" type="xs:boolean" use="optional" default="true"/>
			<xs:attribute name="pattern" type="xs:IDREF" use="optional"/>
			<xs:attribute name="hatching" type="xs:IDREF" use="optional"/> 
		</xs:complexType>
	</xs:element>
	<xs:element name="LinienParams">
		<xs:complexType>
			<xs:attribute name="class" type="xs:IDREF" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PunktParams">
		<xs:complexType>
			<xs:attribute name="symbolId" type="xs:IDREF" use="required"/>
			<xs:attribute name="symbolSize" type="xs:float" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LineTextParams">
		<xs:complexType mixed="false">
			<xs:attribute name="class" type="xs:IDREF" use="required"/>
			<xs:attribute name="text" type="xs:string" use="required"/>
			<xs:attribute name="charSize" type="xs:float" use="optional" default="1.0"/>
			<xs:attribute name="extraFont" type="xs:boolean" use="optional" default="false"/>
			<xs:attribute name="wideChar" type="xs:boolean" use="optional" default="false"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="LineSymbolParams">
		<xs:complexType>
			<xs:attribute name="symbolId" type="xs:IDREF" use="required"/>
			<xs:attribute name="symbolDist" type="xs:float" use="optional"/>
			<xs:attribute name="symbolSize" type="xs:float" use="optional"/>
			<xs:attribute name="symbolAngle" use="optional" type="xs:decimal">
				
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SymbolTabelle">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="SymbolTabellenEintrag" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="attributWert" type="xs:string" use="required"/>
						<xs:attribute name="symbolId" type="xs:IDREF" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="TextTabelle">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="TextTabellenEintrag" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="attributWert" type="xs:string" use="required"/>
						<xs:attribute name="textString" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Enumeration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="EnumItem" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="nameA" type="xs:string" use="required"/>
			<xs:attribute name="nameB" type="xs:string" use="optional"/>
			<xs:attribute name="defaultSymbolSize" type="xs:float" use="optional"/>
			<xs:attribute name="defaultTextStyle" type="xs:IDREF" use="optional"/>
			<xs:attribute name="defaultTextSymbol" type="xs:IDREF" use="optional"/>
			<xs:attribute name="defaultTextSymbolSize" type="xs:float" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnumItem">
		<xs:complexType>
			<xs:attribute name="schluesselNummerA" type="xs:string" use="optional"/>
			<xs:attribute name="schluesselNummerB" type="xs:string" use="optional"/>
			<xs:attribute name="symbolId" type="xs:IDREF" use="optional"/>
			<xs:attribute name="symbolSize" type="xs:float" use="optional"/>
			<xs:attribute name="text" type="xs:string" use="optional"/>
			<xs:attribute name="textStyle" type="xs:IDREF" use="optional"/>
			<xs:attribute name="textSymbol" type="xs:IDREF" use="optional"/>
			<xs:attribute name="textSymbolSize" type="xs:float" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ExternalCodeList">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="EnumItem" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Marker">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded" minOccurs="1">
				<xs:element ref="Path"/>
			</xs:choice>
			<xs:attribute name="name" use="required" type="xs:ID"/>
			<xs:attribute name="viewBox" use="required" type="xs:string"/>			
			<xs:attribute name="refX" use="required" type="xs:decimal"/>
			<xs:attribute name="refY" use="required" type="xs:decimal"/>
			<xs:attribute name="width" use="required" type="xs:decimal"/>
			<xs:attribute name="height" use="required" type="xs:decimal"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== KIT-IAI/GMLToolbox-src/AppConfig/GMLSchemata/XPlanGML_4_1/Stylesheets/Sonst/SvgParamXPlanGML_RPlan_RLP_LEP_III_4_0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Parameter zur SVG-Visualisierung eines Regionalen Entwicklungsplans Rheinland-Pfalz-->

<SvgVisualisierung xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="SvgParameter.xsd"
 gmlType="XPlanGML"
 Masstab="1:2000"
 datum="2009-09-18"
 breiteUeberschrift="800"
 hoeheUeberschrift="30"
 gmlVersion="4.0">
    
    <!--RP_Plan -->
    <GmlKlassenVisual gmlKlassenName="RP_Plan" priorityFlaechendarstellung="50">
        <FlaechenDarstellung default="true">
            <FlaechenParams class="RpRaeumlicherGeltungsbereichA" clip="false"/>
            <FlaechenParams class="RpRaeumlicherGeltungsbereichB" clip="false"/>
        </FlaechenDarstellung>
    </GmlKlassenVisual>        
    
    <Style styleName="RpRaeumlicherGeltungsbereichA">
        <FillColor>
            <None/>
        </FillColor>
        <StrokeColor>
            <Color r="0" g="0" b="0"/>
        </StrokeColor>
        <Stroke-width>4</Stroke-width>
        <Stroke-dasharray>10</Stroke-dasharray>
        <Stroke-dasharray>3</Stroke-dasharray>
        <Stroke-dashoffset>1</Stroke-dashoffset>
    </Style>
    
    <Style styleName="RpRaeumlicherGeltungsbereichB">
        <FillColor>
            <None/>
        </FillColor>
        <StrokeColor>
            <ColorName>black</ColorName>
        </StrokeColor>
        <Stroke-width>0.5</Stroke-width>
    </Style>
    
    <!-- RP_RLP_ZentrlerOrtBesondFunktion Punktdarstellung -->
    <GmlKlassenVisual gmlKlassenName="RP_RLP_ZentralerOrtBesondFunktion"  priorityPunktdarstellung="30" selectAttribut1="funktion" selectAttribut2="netzTyp">
        <PunktDarstellung symbol="SymbolOberzentrum" >
            <SelectAttributWert1>1000</SelectAttributWert1>
            <SelectAttributWert2>IIII</SelectAttributWert2>
        </PunktDarstellung>
        
        <PunktDarstellung symbol="SymbolMittelzentrumGrundnetz">
            <SelectAttributWert1>2000</SelectAttributWert1>
            <SelectAttributWert2>1000</SelectAttributWert2>
        </PunktDarstellung>
        
        <PunktDarstellung symbol="SymbolMittelzentrumErgaenzungsnetz">
            <SelectAttributWert1>2000</SelectAttributWert1>
            <SelectAttributWert2>2000</SelectAttributWert2>
        </PunktDarstellung>
             
        <PunktDarstellung symbol="SymbolGrundzentrum">
            <SelectAttributWert1>3000</SelectAttributWert1>
            <SelectAttributWert2>NNNN</SelectAttributWert2>
        </PunktDarstellung>       
        
        <PunktDarstellung symbol="SymbolGrundzentrumGrundnetz">
            <SelectAttributWert1>3000</SelectAttributWert1>
            <SelectAttributWert2>1000</SelectAttributWert2>
        </PunktDarstellung>  
        
        <PunktDarstellung symbol="SymbolGrundzentrumErgaenzungsnetz">
            <SelectAttributWert1>3000</SelectAttributWert1>
            <SelectAttributWert2>2000</SelectAttributWert2>
        </PunktDarstellung>       
    </GmlKlassenVisual>
    
    <Symbol name="SymbolOberzentrum">
        <Rect  x="-10" y="-10"  width="20" height="20">
            <FillColor>
                <ColorName>red</ColorName>
            </FillColor>
            <StrokeColor>
                <None>/</None>
            </StrokeColor>
        </Rect>
        
        <Rect x="-7.5" y="-7.5"  width="15" height="15">
            <FillColor>
                <ColorName>white</ColorName>
            </FillColor>
            <StrokeColor>
                <None/>
            </StrokeColor>
        </Rect> 
        
        <Rect x="-5" y="-5" width="10" height="10">
            <FillColor>
                 <ColorName>red</ColorName>
            </FillColor>
            <StrokeColor>
                <None/>
            </StrokeColor>
        </Rect>
    </Symbol>
    
    <Symbol name="SymbolMittelzentrumGrundnetz">
        <Rect x="-5" y="-5" width="10" height="10">
            <FillColor>
                <ColorName>red</ColorName>
            </FillColor>
            <StrokeColor>
                <None/>
            </StrokeColor>
        </Rect>        
    </Symbol>
    
    <Symbol name="SymbolMittelzentrumErgaenzungsnetz">
        <Rect x="-4" y="-4" width="8" height="8">
            <FillColor>
           <ColorName>white</ColorName>
            </FillColor>
            <StrokeColor>
               <ColorName>red</ColorName>
            </StrokeColor>
            <Stroke-width>2</Stroke-width>
        </Rect>        
        
       
    </Symbol>
    
    <Symbol name="SymbolGrundzentrum">
        <Circle cx="0" cy="0" r="4">
            <FillColor>
                <ColorName>red</ColorName>
            </FillColor>
            <StrokeColor>
                <None/>
            </StrokeColor>
        </Circle>
    </Symbol>
    
    <Symbol name="SymbolGrundzentrumGrundnetz">
        <Circle cx="0" cy="0" r="4">
            <FillColor>
                <ColorName>red</ColorName>
            </FillColor>
            <StrokeColor>
                <None/>
            </StrokeColor>
        </Circle>
    </Symbol>
    
    <Symbol name="SymbolGrundzentrumErgaenzungsnetz">
        <Circle cx="0" cy="0" r="3.5">
            <FillColor>
                <ColorName>white</ColorName>
            </FillColor>
            <StrokeColor>
              <ColorName>red</ColorName>
            </StrokeColor>
            <Stroke-width>1</Stroke-width>
        </Circle>
    </Symbol>
    
    <!--  RP_RLP_Raumkategorie -->
    <GmlKlassenVisual gmlKlassenName="RP_RLP_Raumkategorie" priorityFlaechendarstellung="10" priorityPunktdarstellung="30" selectAttribut1="typ">
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>1000</SelectAttributWert1>
            <FlaechenParams class="RP-RLP-RaumkategorieFlaechenStyle" clip="true"/>
        </FlaechenDarstellung>
        
        <PunktDarstellung symbol="SymbolFunktionsraum">
            <SelectAttributWert1>1000</SelectAttributWert1>
        </PunktDarstellung>
    </GmlKlassenVisual>
    
    <Style styleName="RP-RLP-RaumkategorieFlaechenStyle">
        <FillColor>
            <None/>
        </FillColor>
        <StrokeColor>
            <ColorName>red</ColorName>
        </StrokeColor>
        <Stroke-width>2</Stroke-width>
    </Style>
    
    <Symbol name="SymbolFunktionsraum">
        <Rect x="-9.5" y="-4.5" width="19" height="9">
            <FillColor>
                <ColorName>white</ColorName>
            </FillColor>
            <StrokeColor>
                <ColorName>red</ColorName>
            </StrokeColor>
            <Stroke-width>1</Stroke-width>
        </Rect>
    </Symbol>
    
    <GmlKlassenVisual gmlKlassenName="RP_RLP_Siedlungsstruktur" priorityFlaechendarstellung="10" selectAttribut2="rechtsstand" selectAttribut3="gebietsTyp" selectAttribut1="typ">
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>1000</SelectAttributWert1>
            <SelectAttributWert2>NNNN</SelectAttributWert2>
            <SelectAttributWert3>NNNN</SelectAttributWert3>
            <FlaechenParams class="RP-RLP-SiedlungflaecheWohnenStyle" clip="false"/>
        </FlaechenDarstellung>
        
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>1000</SelectAttributWert1> 
            <SelectAttributWert2>2000</SelectAttributWert2>
            <SelectAttributWert3>NNNN</SelectAttributWert3>
            <FlaechenParams class="RP-RLP-SiedlungflaecheWohnenBestandStyle" clip="false"/>
        </FlaechenDarstellung>
        
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>1000</SelectAttributWert1>
            <SelectAttributWert2>1000</SelectAttributWert2>
            <SelectAttributWert3>NNNN</SelectAttributWert3>
            <FlaechenParams class="RP-RLP-SiedlungflaecheWohnenPlanungStyle" clip="false"/>
        </FlaechenDarstellung>        
        
        <FlaechenDarstellung deckend="true" priority="12">
            <SelectAttributWert1>1000</SelectAttributWert1>
            <SelectAttributWert2>IIII</SelectAttributWert2>
            <SelectAttributWert3>1000</SelectAttributWert3>
            <FlaechenParams hatching="VorranggebietWohnenHatch" clip="false"/>
        </FlaechenDarstellung>
        
        <FlaechenDarstellung deckend="true" priority="12">
            <SelectAttributWert1>1000</SelectAttributWert1>
            <SelectAttributWert2>IIII</SelectAttributWert2>
            <SelectAttributWert3>2000</SelectAttributWert3>
            <FlaechenParams hatching="VorbehaltsgebietWohnenHatch" clip="false"/>
        </FlaechenDarstellung>
               
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>2000</SelectAttributWert1>
            <SelectAttributWert2>NNNN</SelectAttributWert2>
            <SelectAttributWert3>NNNN</SelectAttributWert3>
            <FlaechenParams class="RP-RLP-SiedlungflaecheIndustrieGewerbeStyle" clip="false"/>
        </FlaechenDarstellung>
        
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>2000</SelectAttributWert1>
            <SelectAttributWert2>2000</SelectAttributWert2>
            <SelectAttributWert3>NNNN</SelectAttributWert3>
            <FlaechenParams class="RP-RLP-SiedlungflaecheIndustrieGewerbeBestandStyle" clip="false"/>
        </FlaechenDarstellung>
        
        <FlaechenDarstellung deckend="true">
            <SelectAttributWert1>2000</SelectAttributWert1>
            <SelectAttributWert2>1000</SelectAttributWert2>
            <SelectAttributWert3>NNNN</SelectAttributWert3>
            <FlaechenParams class="RP-RLP-SiedlungflaecheIndustrieGewerbePlanungStyle" clip="false"/>
        </FlaechenDarstellung>
